### ISSUE TITLE
Artifice Hotfix 1

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1603]
Issue to track/discuss hotfix (@mluessi, @mlyle).

To be fixed:
- [X] RE1: RGB LEDs broken #1587 
- [x] Authors list on Authors screen still empty #1600
- [ ] ~~~GCS: Rfm Bind Wizard Appears Broken #1602~~~
- [x] Failsafe issue #1612

**Comment by mlyle** [comment]
@mluessi --- artifacts are going to spit out soon and I'll upload them to https://github.com/d-ronin/dRonin/releases/tag/Release-20170213.1 within the next couple of hours.  Can you please verify LEDs on RE1 and overall function with RE1 ASAP?  (It's marked pre-release but I'll push it out more generally once you OK.)

Also, your assistance with getting #1523 out of limbo would be appreciated...

**Comment by mlyle** [comment]
@mluessi -- artifacts are up-- will you be able to look at this today?

**Comment by mluessi** [comment]
@mlyle thanks. I'm travelling at the moment without access to hardware to test things. I can test it this weekend.

**Comment by mlyle** [comment]
Shipped
