### ISSUE TITLE
Meta Controls Level Up

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#182]
- [x] ~~ghettomixer (no clipping with 1.0 throttle) https://github.com/d-ronin/dRonin/issues/229~~
- [x] ~~3d mode (reversible ESCs) https://github.com/d-ronin/dRonin/issues/211~~
- [x] ~~"AIR MODE" PIDs at low/configurable/zero throttle for hangtime stabilization. https://github.com/d-ronin/dRonin/issues/228~~

**Comment by fujin** [comment]
@mlyle you've mentioned all of these in the past so wanted to collect 'em somewhere. :)

**Comment by dustin** [comment]
Problem with air-mode is I sometimes really don't want that, but most of the times I do.  It seems like it might make landing hard.

I flew my naze32 with dRonin and an old 180 with baseflight over the weekend.  I cut throttle on both.  dRonin started to dip a little.  baseflight flipped.  Might be comparative balances just working out.

I do like my hangtime, though.  And I sometimes can't lose altitude fast enough because I fear what happens when I cut throttle too much.  It'd be nice to get rid of that as long as we can still land well.

**Comment by mluessi** [comment]
How does this "AIR MODE" stuff work? Any links / documentation?

**Comment by DTFUHF** [comment]
As far as I know, it's Facebook's terminology for a minimum positive thrust state where the copter is still stabilized, so you can descend quickly ( as fast as possible while still oriented upwards ) while keeping orientation stability.

**Comment by tracernz** [comment]
So the PID controller remains active while at minimum throttle. Cleanflight used to have this a while back but they took it away because people complained about the behaviour when landing (the integral causes the motors to wind-up and sort of jump each time the vehicle contacts the ground). It seems it's being re-invented again under a different name.

**Comment by tracernz** [comment]
I propose we split this issue into three separate ones, this one can be renamed to "Preserve control at minimum throttle" or something equally meaningful, since the discussion has been mostly on that topic, #211 covers 3D, and we should create one for ghettomixer with a more descriptive title about what it should actually do.

**Comment by mlyle** [comment]
@tracernz Yes, I think of it this way:

* Ghettomixer with negative clip management that ensures that it is only willing to add 3-5% power for stabilization.  so a 4% throttle can never become more than, say, half the motors at 0% and half the motors at 14%.  (This may be *less* stabilization than before in some circumstances, but more than before when at 0%.  So this should also reduce the tendency to climb at low power from control oscillation/overtuning)
* Significant integral attenuation at very low throttle

**Comment by DTFUHF** [comment]
What's ghettomixer? I'll probably never use it if you keep that name. Is it going to steal my wallet?

**Comment by mlyle** [comment]
Ghettomixer is a clipping management and actuator scaling system that is implemented "wrong" -- proof of concept --- but yields benefits in many circumstances.  I really mean ghettomixer's successor with correct clipping management.

**Comment by tracernz** [comment]
Ok, make an issue for it. It's hard to track when their are multiple issues within one github issue and the title is meaningless. ;-)

**Comment by fujin** [comment]
Logged the other two issues. Closing.
