### ISSUE TITLE
Renatus Technology Preview Release 2 Issue

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#284]
This is a roll-up of stuff needed for R-TPR2

* [x] #237/#286 Usability: widget to select configuration shows up behind splash screen
* [x] #213 License.txt shipping and License.Txt cleanup
* [x] CONFIRM packaging: MacOSX/DMG
* [x] CONFIRM packaging: Windows/Installer
* [x] CONFIRM packaging: Windows/zip
* [x] CONFIRM packaging: Linux/tar
* [x] CONFIRM packaging: Linux/deb
* [ ] ~~NiceToHave: #157 / #279  RTH sequencer merged so we can hopefully get test feedback from @pug398 and others ---- community decision: only merges with flight test~~
* [ ] NiceToHave: #283 GCS finding firmware on all plats (or at least knowing the weaknesses)

**Comment by dustin** [comment]
I'd argue for #75 -- it should be trivial to get a small request in similar to what comes in from autotune results.  Perhaps this can be issued when a board is connected.

**Comment by dustin** [comment]
Also, #287 seems easy and useful.

**Comment by mlyle** [comment]
@dustin Are you familiar with the GCS side of those interchanges at all?  We don't have @tracernz and I'm fairly slow on the GCS side of things.  I really want to get a preview release cut in the next day or two (and expect I'll be rather busy with packaging) -- because we'll get much better feedback with where we are now than the last hastily-cut preview release.

**Comment by dustin** [comment]
I'll take a look.  It's stuff I want, there are examples, and I can build.

**Comment by mlyle** [comment]
Packaging confirmations ticked off in conjunction with #289

**Comment by mlyle** [comment]
User spastic from IRC has used the Windows prototype installer.   Encountered issue #295, but otherwise seems to be doing well.

**Comment by 5PAZT1C** [comment]
migrated from tau labs to this release. so far so good, havent flown it yet. Excited about trying autotune on my cc3d
