### ISSUE TITLE
Stabilization / PR queue maintenance - Tanto -- mpl-kitchensink

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#578]
- [x] #139 pick 3734fe5 Merge remote-tracking branch 'pr/139' into mpl-kitchensink
- [x] ~~#248 pick 37b1819 Merge remote-tracking branch 'pr/248' into mpl-kitchensink~~ Withdrawn
- [x] #411 pick 2893404 Merge remote-tracking branch 'pr/411' into mpl-kitchensink
- [ ] #458 pick ff754d9 Merge remote-tracking branch 'pr/458' into mpl-kitchensink
- [x] ~~#496 pick d3f108e Merge remote-tracking branch 'pr/496' into mpl-kitchensink~~ Merged
- [x] #520 pick bf8512c Merge remote-tracking branch 'pr/520' into mpl-kitchensink
- [x] #563 pick 6d773c9 Merge remote-tracking branch 'pr/563' into mpl-kitchensink
- [x] #457 pick e9db1fd Merge remote-tracking branch 'pr/457' into mpl-kitchensink
- [x] #473 pick 43cabc4 Merge remote-tracking branch 'pr/473' into mpl-kitchensink
- [x] #506 pick 6310d3d Merge remote-tracking branch 'pr/506' into mpl-kitchensink - conflict in comments
