### ISSUE TITLE
KitchenSink test branch housekeeping

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#613]
- [x] ~~#612 07593a3 Merge remote-tracking branch 'pr/612' into mpl-kitchensink / GCS UUID~~ notready
- [ ] #576 aba7743 Merge remote-tracking branch 'pr/576' into mpl-kitchensink / cellcounting
- [x] ~~#524 63d0d81 Merge remote-tracking branch 'pr/524' into mpl-kitchensink / uploader & connect speed~~ notready
- [ ] #458 eb4d086 Merge remote-tracking branch 'pr/458' into mpl-kitchensink / openlog on lux
- [x] #473 bfc86ff Merge remote-tracking branch 'pr/473' into mpl-kitchensink / failsafe flight mode
- [x] #569 cbecdd7 Merge remote-tracking branch 'pr/569' into mpl-kitchensink / moar thrust
- [x] ~~#607 cd00fe7 Merge remote-tracking branch 'pr/607' into mpl-kitchensink / serial init refactor~~ wasnotready
- [x] #608 693b2fa Merge remote-tracking branch 'pr/608' into mpl-kitchensink / clippy
