### ISSUE TITLE
Kitchensink shake-out branch bookkeeping

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#710]
- [x] ~~08c44c9 Merge remote-tracking branch 'pr/711' into mpl-kitchensink #711 weak leveling rates~~ merged
- [ ] c4d607c Merge remote-tracking branch 'pr/708' into mpl-kitchensink #708 sim compile on windows
- [ ] 85fe483 Merge remote-tracking branch 'pr/707' into mpl-kitchensink #707 althold intergal
- [x] ~~d981cbb Merge remote-tracking branch 'pr/704' into mpl-kitchensink #704 remove flash "OTA"~~ merged
- [x] ~~c2e0f51 Merge remote-tracking branch 'pr/697' into mpl-kitchensink #697 gcs hangtime settings~~ merged
- [x] ~~1ca47e4 Merge remote-tracking branch 'pr/696' into mpl-kitchensink #696 setupwiz always requests reboot~~ merged
- [x] ~~522d4ae Merge remote-tracking branch 'pr/693' into mpl-kitchensink #693 gcs CWD / save dialog~~ merged
- [x] 3d474f0 Merge remote-tracking branch 'pr/691' into mpl-kitchensink #691 failsafe disarm timer
- [x] e37d1b8 Merge remote-tracking branch 'pr/690' into mpl-kitchensink #690 shortcutsettings remove
- [x] ~~6a4ff72 Merge remote-tracking branch 'pr/676' into mpl-kitchensink #676 lowpowerstab~~ merged
- [x] ~~779f199 Merge remote-tracking branch 'pr/617' into mpl-kitchensink #617 revo flexio uart~~ merged
- [x] ~~e89ddff Merge remote-tracking branch 'pr/576' into mpl-kitchensink #576~~ cellcountcalc -- defer/polish

**Comment by mlyle** [comment]
artifacts will show up here: http://jar.lyle.org:8080/job/dronin/189/

**Comment by mlyle** [comment]
Kitchensink sequence 1 will be on lux; hope to evaluate 576, 676, 690, 691, 693, 696, 697, 704, 711.

**Comment by mlyle** [comment]
Updated kitchensink for failsafe change in 676.

artifacts will show up here: http://jar.lyle.org:8080/job/dronin/192/

**Comment by pug398** [comment]
On kitchen2, sparky2 has a constant actuator warning that is not on next 5fde.

**Comment by mlyle** [comment]
@pug398 -- bug #699 -- if we're unable to meet roll/pitch command because of clipping, we now actuator alarm.  Unfortunately this includes the case when we can't because there's no throttle.

Wow, you're brave flying this :P  

Low power stabilization is fun on small craft.  Have not dared to try it on large ones.

**Comment by mlyle** [comment]
#690 / #691 are the last thigns I hope are mergeable form this test pass, and I think they'll be reviewed soon.  So closing this bookkeeping issue for this kitchensink.
