### ISSUE TITLE
Known issues with upgrade meta-issue

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#821]
After #801 lands, known items for cleanup.
- [x] Missing ID complaint during import --- fix for this in #833 
- [x] Failed to connect device: ____ popup https://github.com/d-ronin/dRonin/pull/801#issuecomment-200162563  fixed in #836
- [x] Blank flight controllers need to be handled better - fix for this in #851
- [x] Can't import settings for not-running modules - fix for this in #838
- [x] Completion screen should look better -- fix for this in #837 
- [x] Issues with window height / focus, though these are problematic to address -- fix for this in #837 too
- [x] Verification of availability of cloud service, etc, in the beginning - fix for this in #851
- [x] Better text on first dialog asking about upgrade - fix for this in #851
- [x] Need to not upgrade pipxtreme this way, or bug user in the same way about Naze32-- fixed in #834 
- [x] Add git information for Tau Labs and BrainFPV Tau Labs fork to cloud service to make it a smoother experience for users coming from these platforms. -- done by @dustin

**Comment by tracernz** [comment]
Should it be a modal dialog? I see it sometimes ends up behind the main window (e.g. if an error occurs).

**Comment by mlyle** [comment]
It is setmodal.  There are odd things with modalness and our main window.  (if you have more than one modal thing, Qt acts weird, etc).

**Comment by mlyle** [comment]
P.S.  This is also why most of the errors/subsidary things have been moved into the main dialog.
